name: Build App
on:
    workflow_dispatch:
        inputs:
            os:
                type: choice
                description: OS to build on. Ubuntu is faster, MacOS supports iOS builds
                options:
                    - macos-latest
                    - ubuntu-latest
            platform:
                type: choice
                description: Platform to build for
                options:
                    - android
                    - ios
            profile:
                type: choice
                description: Build profile to use
                options:
                    - development
                    - preview
                    - production
            should_submit:
                type: boolean
                description: Whether to perform the submit step
                required: true
                default: true
jobs:
    build:
        runs-on: ${{ github.event.inputs.os }}
        strategy:
            matrix:
                node: [22.x]
        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: 🏗 Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: pnpm

            - name: 🏗 Setup Java
              if: ${{ github.event.inputs.platform == 'android' }}
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - name: 🏗 Setup Expo and EAS
              uses: expo/expo-github-action@v7
              with:
                  token: ${{ secrets.EXPO_TOKEN }}
                  expo-version: latest
                  eas-version: latest

            - name: 📦 Install dependencies
              run: pnpm install

            - name: 🔢 Increment build number
              run: |
                if [ "${{ github.event.inputs.platform }}" == "android" ]; then
                  # Get current version code from app.config.js
                  CURRENT_VERSION=$(grep -oP 'versionCode: \K\d+' app.config.js || echo "1")
                  NEW_VERSION=$((CURRENT_VERSION + 1))
                  # Update version code in app.config.js
                  if grep -q "versionCode:" app.config.js; then
                    sed -i "s/versionCode: $CURRENT_VERSION/versionCode: $NEW_VERSION/" app.config.js
                  else
                    # Add versionCode to android config if it doesn't exist
                    sed -i '/android: {/a \            versionCode: '"$NEW_VERSION"',' app.config.js
                  fi
                else
                  # Get current build number from app.config.js
                  CURRENT_BUILD=$(grep -oP 'buildNumber: \K\d+' app.config.js || echo "1")
                  NEW_BUILD=$((CURRENT_BUILD + 1))
                  # Update build number in app.config.js
                  if grep -q "buildNumber:" app.config.js; then
                    sed -i "s/buildNumber: $CURRENT_BUILD/buildNumber: $NEW_BUILD/" app.config.js
                  else
                    # Add buildNumber to ios config if it doesn't exist
                    sed -i '/ios: {/a \            buildNumber: '"$NEW_BUILD"',' app.config.js
                  fi
                fi
                # Commit the change
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git add app.config.js
                git commit -m "ci: increment ${{ github.event.inputs.platform }} build number"
                git push

            - name: 👷 Build app
              run: |
                  eas build --local \
                    --non-interactive \
                    --output=./app-build \
                    --platform=${{ github.event.inputs.platform }} \
                    --profile=${{ github.event.inputs.profile }}

            - name: 🚢 Submit
              if: ${{ github.event.inputs.should_submit }}
              run: eas submit -p ${{ github.event.inputs.platform }} --profile ${{ github.event.inputs.profile }} --path app-build

            - name: 📦 Create GitHub Release
              if: ${{ github.event.inputs.platform == 'android' && github.event.inputs.profile == 'production' }}
              uses: softprops/action-gh-release@v1
              with:
                files: app-build/*.apk
                generate_release_notes: true
                draft: false
                prerelease: false
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
